plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.1.cjs

npmRegistries:
  'https://registry.npmjs.org':
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_AUTH_TOKEN:-}
