name: back-kit-engine CI

env:
  context: ./

on:
  push:
    branches: [ main ]
    tags: ['*']
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          show-progress: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - run: npx playwright install --with-deps
      - run: yarn install --immutable
      - run: yarn coverage:ci

      - name: Coveralls
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
        continue-on-error: true
        with:
          path-to-lcov: '${{ env.context }}coverage/lcov.info'
          base-path: '${{ env.context }}'
      - name: Compile file and build
        if: ${{ (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' || github.base_ref == 'main') && matrix.node-version == '18.x' }}
        run: yarn build
      - name: Cache dist directory
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: dist-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ env.context }}dist
          key: ${{ runner.os }}-dist-${{ github.sha }}

  release:
    needs: ['test']
    if: ${{ (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          show-progress: false
      - name: Use Node.js 24.x
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24.x
          check-latest: true
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
          scope: '@micro-lc'
      - name: Cache Pull
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ${{ env.context }}dist
          key: ${{ runner.os }}-dist-${{ github.sha }}
      - run: yarn npm publish
